server:
  port: 8104

spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:mysql://localhost:3306/amazon
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  zipkin:
    base-url: http://localhost:9411
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
