server:
  port: 8104

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3306/amazon
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  zipkin:
    base-url: http://localhost:9411
    enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
