server:
  port: 8107

spring:
  application:
    name: notification-service

  zipkin:
    base-url: http://localhost:9411
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
